# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

joint1_controller:
  type: effort_controllers/JointEffortController
  joint: base_link__link_1

# joint1_controller:
#   type: effort_controllers/JointVelocityController
#   joint: base_link__link_1
#   pid: {p: 700.0, i: 50, d: 70.0}

# joint1_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: base_link__link_1
#   pid: {p: 700.0, i: 50, d: 70.0}